/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.onddo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Picking service. Represents a row in the &quot;Onddo_Picking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.sareweb.onddo.model.impl.PickingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.sareweb.onddo.model.impl.PickingImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see Picking
 * @see net.sareweb.onddo.model.impl.PickingImpl
 * @see net.sareweb.onddo.model.impl.PickingModelImpl
 * @generated
 */
public interface PickingModel extends BaseModel<Picking> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a picking model instance should use the {@link Picking} interface instead.
	 */

	/**
	 * Returns the primary key of this picking.
	 *
	 * @return the primary key of this picking
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this picking.
	 *
	 * @param primaryKey the primary key of this picking
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the picking ID of this picking.
	 *
	 * @return the picking ID of this picking
	 */
	public long getPickingId();

	/**
	 * Sets the picking ID of this picking.
	 *
	 * @param pickingId the picking ID of this picking
	 */
	public void setPickingId(long pickingId);

	/**
	 * Returns the company ID of this picking.
	 *
	 * @return the company ID of this picking
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this picking.
	 *
	 * @param companyId the company ID of this picking
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this picking.
	 *
	 * @return the user ID of this picking
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this picking.
	 *
	 * @param userId the user ID of this picking
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this picking.
	 *
	 * @return the user uuid of this picking
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this picking.
	 *
	 * @param userUuid the user uuid of this picking
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this picking.
	 *
	 * @return the create date of this picking
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this picking.
	 *
	 * @param createDate the create date of this picking
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this picking.
	 *
	 * @return the modified date of this picking
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this picking.
	 *
	 * @param modifiedDate the modified date of this picking
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the type of this picking.
	 *
	 * @return the type of this picking
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this picking.
	 *
	 * @param type the type of this picking
	 */
	public void setType(String type);

	/**
	 * Returns the lat of this picking.
	 *
	 * @return the lat of this picking
	 */
	public double getLat();

	/**
	 * Sets the lat of this picking.
	 *
	 * @param lat the lat of this picking
	 */
	public void setLat(double lat);

	/**
	 * Returns the lng of this picking.
	 *
	 * @return the lng of this picking
	 */
	public double getLng();

	/**
	 * Sets the lng of this picking.
	 *
	 * @param lng the lng of this picking
	 */
	public void setLng(double lng);

	/**
	 * Returns the moon phase of this picking.
	 *
	 * @return the moon phase of this picking
	 */
	@AutoEscape
	public String getMoonPhase();

	/**
	 * Sets the moon phase of this picking.
	 *
	 * @param moonPhase the moon phase of this picking
	 */
	public void setMoonPhase(String moonPhase);

	/**
	 * Returns the weather of this picking.
	 *
	 * @return the weather of this picking
	 */
	@AutoEscape
	public String getWeather();

	/**
	 * Sets the weather of this picking.
	 *
	 * @param weather the weather of this picking
	 */
	public void setWeather(String weather);

	/**
	 * Returns the temperature of this picking.
	 *
	 * @return the temperature of this picking
	 */
	public double getTemperature();

	/**
	 * Sets the temperature of this picking.
	 *
	 * @param temperature the temperature of this picking
	 */
	public void setTemperature(double temperature);

	/**
	 * Returns the humidity of this picking.
	 *
	 * @return the humidity of this picking
	 */
	public double getHumidity();

	/**
	 * Sets the humidity of this picking.
	 *
	 * @param humidity the humidity of this picking
	 */
	public void setHumidity(double humidity);

	/**
	 * Returns the img ID of this picking.
	 *
	 * @return the img ID of this picking
	 */
	public long getImgId();

	/**
	 * Sets the img ID of this picking.
	 *
	 * @param imgId the img ID of this picking
	 */
	public void setImgId(long imgId);

	/**
	 * Returns the img name of this picking.
	 *
	 * @return the img name of this picking
	 */
	@AutoEscape
	public String getImgName();

	/**
	 * Sets the img name of this picking.
	 *
	 * @param imgName the img name of this picking
	 */
	public void setImgName(String imgName);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Picking picking);

	public int hashCode();

	public CacheModel<Picking> toCacheModel();

	public Picking toEscapedModel();

	public String toString();

	public String toXmlString();
}