/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.onddo.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.sareweb.onddo.model.Picking;
import net.sareweb.onddo.service.PickingLocalServiceUtil;

/**
 * The extended model base implementation for the Picking service. Represents a row in the &quot;Onddo_Picking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PickingImpl}.
 * </p>
 *
 * @author A.Galdos
 * @see PickingImpl
 * @see net.sareweb.onddo.model.Picking
 * @generated
 */
public abstract class PickingBaseImpl extends PickingModelImpl
	implements Picking {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a picking model instance should use the {@link Picking} interface instead.
	 */
	public void persist() throws SystemException {
		PickingLocalServiceUtil.updatePicking(this);
	}
}